apiVersion: skaffold/v2alpha3
kind: Config
deploy:
   kubectl:
      manifests:
         - ./infra/k8s/*
build:
   local:
      push: false
   artifacts:
      - image: rawatdevesh/client
        context: client
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: 'src/**/*.js'
                dest: .
      - image: rawatdevesh/comments
        context: comments
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: rawatdevesh/event-bus
        context: event-bus
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: rawatdevesh/modretor
        context: modretor
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: rawatdevesh/posts
        context: posts
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
      - image: rawatdevesh/query
        context: query
        docker:
           dockerfile: Dockerfile
        sync:
           manual:
              - src: '*.js'
                dest: .
